name: run scrape.py

on:
  schedule:
    - cron: '0 9 * * *' 
  push:
    branches: 
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
    
      - name: install requirement packages
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: execute script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          URL: ${{ secrets.URL }}
        run: python scrape.py